---
title: Kitab Ghar
# timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
baseurl: "/Kitab_Ghar"
url: https://kitabghar.github.io/
markdown: kramdown
permalink: pretty
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll/tagging
- jekyll-seo-tag
paginate: 5
paginate_path: "/page/:num"
include:
- _pages
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
sass:
  sass_dir: _sass
  style: compressed
